### ISSUE TITLE
0.53

### ISSUE THREAD

**Issue by rejetto** [8gudbits/hfs-dracula-theme#1]
hey, i like your theme!
i suggest you to add these new details to your `plugin.js`
```
exports.isTheme = "dark"
exports.preview = "https://github.com/TechWhizKid/hfs-dracula-theme/raw/main/preview.png"
```

these are effective starting with version 0.53.0-alpha5

**Comment by TechWhizKid** [comment]
Thank you for your suggestion! I have implemented the changes you recommended in the plugin.js file.

**Comment by 8gudbits** [comment]
Thank you for your suggestion! I have implemented the changes you recommended in the `plugin.js` file.
